### ISSUE TITLE
Error when slideshow wants to fetch artworks

### ISSUE THREAD

**Issue by benni3005** [pkscout/script.artistslideshow#42]
Until recently the addon worked fine, but right now I only get this error message in `kodi.log` when starting the visualization:

```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.AttributeError'>
Error Contents: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_STATIC_CALLBACKS'
Traceback (most recent call last):
  File "/home/username/.kodi/addons/script.artistslideshow/default.py", line 30, in <module>
	from resources.common.url import URL
  File "/home/username/.kodi/addons/script.artistslideshow/resources/common/url.py", line 4, in <module>
	import requests as _requests
  File "/home/username/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 53, in <module>
	from .packages.urllib3.contrib import pyopenssl
  File "/home/username/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 54, in <module>
	import OpenSSL.SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
	from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
	from OpenSSL._util import (
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
	from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 68, in <module>
	error=-1)
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 54, in wrapper
	if lib.Cryptography_STATIC_CALLBACKS:
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_STATIC_CALLBACKS'
-->End of Python script error report<--
```

My Kodi version is 14.1 on a Ubuntu 14.04 LTS, the version of the addon itself is 1.8.7. Could it be the error resolves itself when upgrading Kodi to the most recent version? Last time I upgraded it gave me some minor headaches, so I'm a little bit hesitating on doing so.

Best regards,
Benni

**Comment by pkscout** [comment]
It looks like the issue is either in the requests module or in the openSSL that's packaged with Kodi.  Upgrading to 15.x might resolve that.  I don't have Kodi 14 on anything anymore, so I can't really troubleshoot.  I suspect when Kodi 16 comes out of beta I'll be dropping support for 14 anyway.  I'll leave this open for a bit.  If you have issues after upgrading, you can just post here.  If you do, please include the full Kodi debug log and turn on the debug logging in AS (it's in the settings).  That way I can see what led up to the crash.

**Comment by benni3005** [comment]
I just upgraded to Kodi v15.2 and the only thing irritating me was the missing language, which I now had to install as addon. Your addon now works fine and shows artist images again :)
